### ISSUE TITLE
Request: annotations to do additional stuff.

### ISSUE THREAD

**Issue by joshmanders** [caddyserver/ingress#122] opened 2023-03-08 23:21 UTC
Can someone either help me by pointing me in the direction to figure this stuff out, or can I request something be done to add the ability to customize how Caddy works a bit using annotations.

For example the biggest thing missing right now, which I'm surprised hasn't been talked about, which makes me wonder how widely used this is, heh... Is redirecting`www` to `no-www` and vice versa. 

I tried looking through the codebase but I just don't know Caddy well enough outside of being a user, kubernetes, nor this ingress codebase, so I'm not sure how trivial this would be to implement, but if I can get some guidance I can try to submit a PR.

**Comment by unixfox** [comment] 2023-03-08 23:49
Duplicate of https://github.com/caddyserver/ingress/issues/37

**Comment by felicianotech** [comment] 2023-09-30 05:38
@unixfox This is related but not a duplicate.

The Nginx ingress has many annotations for tasks like this. The one Embraser01 mentioned would work but is more general. They have one specific to this use case: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#redirect-fromto-www

**Comment by mavimo** [comment] 2023-12-06 19:15
@joshmanders the redirect functionality contributed by @Xinayder in #165 is now merged not sure if it cover 100% of your needs, but let us know 😄

**Closed** 2023-12-06 19:33 UTC
